// ─── ISO 3166-1 alpha-2 → Full country name ───────────────────────────────────
// Allows getCurrencySymbol() to accept either "UG" or "Uganda" etc.
const ISO2_TO_COUNTRY = {
  DZ: 'Algeria', AO: 'Angola', BJ: 'Benin', BW: 'Botswana',
  BF: 'Burkina Faso', BI: 'Burundi', CV: 'Cabo Verde', CM: 'Cameroon',
  CF: 'Central African Republic', TD: 'Chad', KM: 'Comoros', CG: 'Congo',
  CD: 'DR Congo', DJ: 'Djibouti', EG: 'Egypt', GQ: 'Equatorial Guinea',
  ER: 'Eritrea', SZ: 'Eswatini', ET: 'Ethiopia', GA: 'Gabon',
  GM: 'Gambia', GH: 'Ghana', GN: 'Guinea', GW: 'Guinea-Bissau',
  CI: 'Ivory Coast', KE: 'Kenya', LS: 'Lesotho', LR: 'Liberia',
  LY: 'Libya', MG: 'Madagascar', MW: 'Malawi', ML: 'Mali',
  MR: 'Mauritania', MU: 'Mauritius', MA: 'Morocco', MZ: 'Mozambique',
  NA: 'Namibia', NE: 'Niger', NG: 'Nigeria', RW: 'Rwanda',
  ST: 'Sao Tome and Principe', SN: 'Senegal', SC: 'Seychelles',
  SL: 'Sierra Leone', SO: 'Somalia', ZA: 'South Africa',
  SS: 'South Sudan', SD: 'Sudan', TZ: 'Tanzania', TG: 'Togo',
  TN: 'Tunisia', UG: 'Uganda', ZM: 'Zambia', ZW: 'Zimbabwe',

  AF: 'Afghanistan', AM: 'Armenia', AZ: 'Azerbaijan', BH: 'Bahrain',
  BD: 'Bangladesh', BT: 'Bhutan', BN: 'Brunei', KH: 'Cambodia',
  CN: 'China', CY: 'Cyprus', GE: 'Georgia', IN: 'India',
  ID: 'Indonesia', IR: 'Iran', IQ: 'Iraq', IL: 'Israel',
  JP: 'Japan', JO: 'Jordan', KZ: 'Kazakhstan', KW: 'Kuwait',
  KG: 'Kyrgyzstan', LA: 'Laos', LB: 'Lebanon', MY: 'Malaysia',
  MV: 'Maldives', MN: 'Mongolia', MM: 'Myanmar', NP: 'Nepal',
  KP: 'North Korea', OM: 'Oman', PK: 'Pakistan', PS: 'Palestine',
  PH: 'Philippines', QA: 'Qatar', SA: 'Saudi Arabia', SG: 'Singapore',
  KR: 'South Korea', LK: 'Sri Lanka', SY: 'Syria', TW: 'Taiwan',
  TJ: 'Tajikistan', TH: 'Thailand', TL: 'Timor-Leste', TR: 'Turkey',
  TM: 'Turkmenistan', AE: 'United Arab Emirates', UZ: 'Uzbekistan',
  VN: 'Vietnam', YE: 'Yemen',

  AL: 'Albania', AD: 'Andorra', AT: 'Austria', BY: 'Belarus',
  BE: 'Belgium', BA: 'Bosnia and Herzegovina', BG: 'Bulgaria',
  HR: 'Croatia', CZ: 'Czech Republic', DK: 'Denmark', EE: 'Estonia',
  FI: 'Finland', FR: 'France', DE: 'Germany', GR: 'Greece',
  HU: 'Hungary', IS: 'Iceland', IE: 'Ireland', IT: 'Italy',
  XK: 'Kosovo', LV: 'Latvia', LI: 'Liechtenstein', LT: 'Lithuania',
  LU: 'Luxembourg', MT: 'Malta', MD: 'Moldova', MC: 'Monaco',
  ME: 'Montenegro', NL: 'Netherlands', MK: 'North Macedonia',
  NO: 'Norway', PL: 'Poland', PT: 'Portugal', RO: 'Romania',
  RU: 'Russia', SM: 'San Marino', RS: 'Serbia', SK: 'Slovakia',
  SI: 'Slovenia', ES: 'Spain', SE: 'Sweden', CH: 'Switzerland',
  UA: 'Ukraine', GB: 'United Kingdom', VA: 'Vatican City',

  AG: 'Antigua and Barbuda', AR: 'Argentina', BS: 'Bahamas',
  BB: 'Barbados', BZ: 'Belize', BO: 'Bolivia', BR: 'Brazil',
  CA: 'Canada', CL: 'Chile', CO: 'Colombia', CR: 'Costa Rica',
  CU: 'Cuba', DM: 'Dominica', DO: 'Dominican Republic',
  EC: 'Ecuador', SV: 'El Salvador', GD: 'Grenada', GT: 'Guatemala',
  GY: 'Guyana', HT: 'Haiti', HN: 'Honduras', JM: 'Jamaica',
  MX: 'Mexico', NI: 'Nicaragua', PA: 'Panama', PY: 'Paraguay',
  PE: 'Peru', KN: 'Saint Kitts and Nevis', LC: 'Saint Lucia',
  VC: 'Saint Vincent and the Grenadines', SR: 'Suriname',
  TT: 'Trinidad and Tobago', US: 'United States', UY: 'Uruguay',
  VE: 'Venezuela',

  AU: 'Australia', FJ: 'Fiji', KI: 'Kiribati', MH: 'Marshall Islands',
  FM: 'Micronesia', NR: 'Nauru', NZ: 'New Zealand', PW: 'Palau',
  PG: 'Papua New Guinea', WS: 'Samoa', SB: 'Solomon Islands',
  TO: 'Tonga', TV: 'Tuvalu', VU: 'Vanuatu',
};

export const COUNTRY_CURRENCY_MAP = {
    // Africa
    Algeria: 'DZD', Angola: 'AOA', Benin: 'XOF', Botswana: 'BWP',
    'Burkina Faso': 'XOF', Burundi: 'BIF', 'Cabo Verde': 'CVE',
    Cameroon: 'XAF', 'Central African Republic': 'XAF', Chad: 'XAF',
    Comoros: 'KMF', Congo: 'XAF', 'DR Congo': 'CDF', Djibouti: 'DJF',
    Egypt: 'EGP', 'Equatorial Guinea': 'XAF', Eritrea: 'ERN',
    Eswatini: 'SZL', Ethiopia: 'ETB', Gabon: 'XAF', Gambia: 'GMD',
    Ghana: 'GHS', Guinea: 'GNF', 'Guinea-Bissau': 'XOF',
    'Ivory Coast': 'XOF', Kenya: 'KES', Lesotho: 'LSL', Liberia: 'LRD',
    Libya: 'LYD', Madagascar: 'MGA', Malawi: 'MWK', Mali: 'XOF',
    Mauritania: 'MRU', Mauritius: 'MUR', Morocco: 'MAD',
    Mozambique: 'MZN', Namibia: 'NAD', Niger: 'XOF', Nigeria: 'NGN',
    Rwanda: 'RWF', 'Sao Tome and Principe': 'STN', Senegal: 'XOF',
    Seychelles: 'SCR', 'Sierra Leone': 'SLL', Somalia: 'SOS',
    'South Africa': 'ZAR', 'South Sudan': 'SSP', Sudan: 'SDG',
    Tanzania: 'TZS', Togo: 'XOF', Tunisia: 'TND', Uganda: 'UGX',
    Zambia: 'ZMW', Zimbabwe: 'ZWL',

    // Asia
    Afghanistan: 'AFN', Armenia: 'AMD', Azerbaijan: 'AZN',
    Bahrain: 'BHD', Bangladesh: 'BDT', Bhutan: 'BTN', Brunei: 'BND',
    Cambodia: 'KHR', China: 'CNY', Cyprus: 'EUR', Georgia: 'GEL',
    India: 'INR', Indonesia: 'IDR', Iran: 'IRR', Iraq: 'IQD',
    Israel: 'ILS', Japan: 'JPY', Jordan: 'JOD', Kazakhstan: 'KZT',
    Kuwait: 'KWD', Kyrgyzstan: 'KGS', Laos: 'LAK', Lebanon: 'LBP',
    Malaysia: 'MYR', Maldives: 'MVR', Mongolia: 'MNT', Myanmar: 'MMK',
    Nepal: 'NPR', 'North Korea': 'KPW', Oman: 'OMR', Pakistan: 'PKR',
    Palestine: 'ILS', Philippines: 'PHP', Qatar: 'QAR',
    'Saudi Arabia': 'SAR', Singapore: 'SGD', 'South Korea': 'KRW',
    'Sri Lanka': 'LKR', Syria: 'SYP', Taiwan: 'TWD', Tajikistan: 'TJS',
    Thailand: 'THB', 'Timor-Leste': 'USD', Turkey: 'TRY',
    Turkmenistan: 'TMT', 'United Arab Emirates': 'AED',
    Uzbekistan: 'UZS', Vietnam: 'VND', Yemen: 'YER',

    // Europe
    Albania: 'ALL', Andorra: 'EUR', Austria: 'EUR', Belarus: 'BYN',
    Belgium: 'EUR', 'Bosnia and Herzegovina': 'BAM', Bulgaria: 'BGN',
    Croatia: 'EUR', 'Czech Republic': 'CZK', Denmark: 'DKK',
    Estonia: 'EUR', Finland: 'EUR', France: 'EUR', Germany: 'EUR',
    Greece: 'EUR', Hungary: 'HUF', Iceland: 'ISK', Ireland: 'EUR',
    Italy: 'EUR', Kosovo: 'EUR', Latvia: 'EUR', Liechtenstein: 'CHF',
    Lithuania: 'EUR', Luxembourg: 'EUR', Malta: 'EUR', Moldova: 'MDL',
    Monaco: 'EUR', Montenegro: 'EUR', Netherlands: 'EUR',
    'North Macedonia': 'MKD', Norway: 'NOK', Poland: 'PLN',
    Portugal: 'EUR', Romania: 'RON', Russia: 'RUB', 'San Marino': 'EUR',
    Serbia: 'RSD', Slovakia: 'EUR', Slovenia: 'EUR', Spain: 'EUR',
    Sweden: 'SEK', Switzerland: 'CHF', Ukraine: 'UAH',
    'United Kingdom': 'GBP', 'Vatican City': 'EUR',

    // Americas
    'Antigua and Barbuda': 'XCD', Argentina: 'ARS', Bahamas: 'BSD',
    Barbados: 'BBD', Belize: 'BZD', Bolivia: 'BOB', Brazil: 'BRL',
    Canada: 'CAD', Chile: 'CLP', Colombia: 'COP', 'Costa Rica': 'CRC',
    Cuba: 'CUP', Dominica: 'XCD', 'Dominican Republic': 'DOP',
    Ecuador: 'USD', 'El Salvador': 'USD', Grenada: 'XCD',
    Guatemala: 'GTQ', Guyana: 'GYD', Haiti: 'HTG', Honduras: 'HNL',
    Jamaica: 'JMD', Mexico: 'MXN', Nicaragua: 'NIO', Panama: 'PAB',
    Paraguay: 'PYG', Peru: 'PEN', 'Saint Kitts and Nevis': 'XCD',
    'Saint Lucia': 'XCD', 'Saint Vincent and the Grenadines': 'XCD',
    Suriname: 'SRD', 'Trinidad and Tobago': 'TTD',
    'United States': 'USD', Uruguay: 'UYU', Venezuela: 'VES',

    // Oceania
    Australia: 'AUD', Fiji: 'FJD', Kiribati: 'AUD',
    'Marshall Islands': 'USD', Micronesia: 'USD', Nauru: 'AUD',
    'New Zealand': 'NZD', Palau: 'USD', 'Papua New Guinea': 'PGK',
    Samoa: 'WST', 'Solomon Islands': 'SBD', Tonga: 'TOP',
    Tuvalu: 'AUD', Vanuatu: 'VUV',
};

export const CURRENCY_META = {
    DZD: { symbol: 'د.ج', name: 'Algerian Dinar' },
    AOA: { symbol: 'Kz', name: 'Angolan Kwanza' },
    XOF: { symbol: 'CFA', name: 'West African CFA Franc' },
    BWP: { symbol: 'P', name: 'Botswana Pula' },
    BIF: { symbol: 'Fr', name: 'Burundian Franc' },
    CVE: { symbol: '$', name: 'Cape Verdean Escudo' },
    XAF: { symbol: 'CFA', name: 'Central African CFA Franc' },
    KMF: { symbol: 'Fr', name: 'Comorian Franc' },
    CDF: { symbol: 'Fr', name: 'Congolese Franc' },
    DJF: { symbol: 'Fr', name: 'Djiboutian Franc' },
    EGP: { symbol: 'E£', name: 'Egyptian Pound' },
    ERN: { symbol: 'Nfk', name: 'Eritrean Nakfa' },
    SZL: { symbol: 'L', name: 'Eswatini Lilangeni' },
    ETB: { symbol: 'Br', name: 'Ethiopian Birr' },
    GMD: { symbol: 'D', name: 'Gambian Dalasi' },
    GHS: { symbol: '₵', name: 'Ghanaian Cedi' },
    GNF: { symbol: 'Fr', name: 'Guinean Franc' },
    KES: { symbol: 'KSh', name: 'Kenyan Shilling' },
    LSL: { symbol: 'L', name: 'Lesotho Loti' },
    LRD: { symbol: '$', name: 'Liberian Dollar' },
    LYD: { symbol: 'LD', name: 'Libyan Dinar' },
    MGA: { symbol: 'Ar', name: 'Malagasy Ariary' },
    MWK: { symbol: 'MK', name: 'Malawian Kwacha' },
    MRU: { symbol: 'UM', name: 'Mauritanian Ouguiya' },
    MUR: { symbol: '₨', name: 'Mauritian Rupee' },
    MAD: { symbol: 'د.م.', name: 'Moroccan Dirham' },
    MZN: { symbol: 'MT', name: 'Mozambican Metical' },
    NAD: { symbol: '$', name: 'Namibian Dollar' },
    NGN: { symbol: '₦', name: 'Nigerian Naira' },
    RWF: { symbol: 'FRw', name: 'Rwandan Franc' },
    STN: { symbol: 'Db', name: 'São Tomé Dobra' },
    SCR: { symbol: '₨', name: 'Seychellois Rupee' },
    SLL: { symbol: 'Le', name: 'Sierra Leonean Leone' },
    SOS: { symbol: 'Sh', name: 'Somali Shilling' },
    ZAR: { symbol: 'R', name: 'South African Rand' },
    SSP: { symbol: '£', name: 'South Sudanese Pound' },
    SDG: { symbol: '£', name: 'Sudanese Pound' },
    TZS: { symbol: 'TSh', name: 'Tanzanian Shilling' },
    TND: { symbol: 'د.ت', name: 'Tunisian Dinar' },
    UGX: { symbol: 'UGX', name: 'Ugandan Shilling' },
    ZMW: { symbol: 'ZK', name: 'Zambian Kwacha' },
    ZWL: { symbol: '$', name: 'Zimbabwean Dollar' },
    AFN: { symbol: '؋', name: 'Afghan Afghani' },
    AMD: { symbol: '֏', name: 'Armenian Dram' },
    AZN: { symbol: '₼', name: 'Azerbaijani Manat' },
    BHD: { symbol: 'BD', name: 'Bahraini Dinar' },
    BDT: { symbol: '৳', name: 'Bangladeshi Taka' },
    BTN: { symbol: 'Nu', name: 'Bhutanese Ngultrum' },
    BND: { symbol: '$', name: 'Brunei Dollar' },
    KHR: { symbol: '៛', name: 'Cambodian Riel' },
    CNY: { symbol: '¥', name: 'Chinese Yuan' },
    GEL: { symbol: '₾', name: 'Georgian Lari' },
    INR: { symbol: '₹', name: 'Indian Rupee' },
    IDR: { symbol: 'Rp', name: 'Indonesian Rupiah' },
    IRR: { symbol: '﷼', name: 'Iranian Rial' },
    IQD: { symbol: 'ع.د', name: 'Iraqi Dinar' },
    ILS: { symbol: '₪', name: 'Israeli Shekel' },
    JPY: { symbol: '¥', name: 'Japanese Yen' },
    JOD: { symbol: 'JD', name: 'Jordanian Dinar' },
    KZT: { symbol: '₸', name: 'Kazakhstani Tenge' },
    KWD: { symbol: 'KD', name: 'Kuwaiti Dinar' },
    KGS: { symbol: 'лв', name: 'Kyrgyzstani Som' },
    LAK: { symbol: '₭', name: 'Lao Kip' },
    LBP: { symbol: 'L£', name: 'Lebanese Pound' },
    MYR: { symbol: 'RM', name: 'Malaysian Ringgit' },
    MVR: { symbol: 'Rf', name: 'Maldivian Rufiyaa' },
    MNT: { symbol: '₮', name: 'Mongolian Tögrög' },
    MMK: { symbol: 'K', name: 'Myanmar Kyat' },
    NPR: { symbol: '₨', name: 'Nepalese Rupee' },
    KPW: { symbol: '₩', name: 'North Korean Won' },
    OMR: { symbol: '﷼', name: 'Omani Rial' },
    PKR: { symbol: '₨', name: 'Pakistani Rupee' },
    PHP: { symbol: '₱', name: 'Philippine Peso' },
    QAR: { symbol: '﷼', name: 'Qatari Riyal' },
    SAR: { symbol: '﷼', name: 'Saudi Riyal' },
    SGD: { symbol: 'S$', name: 'Singapore Dollar' },
    KRW: { symbol: '₩', name: 'South Korean Won' },
    LKR: { symbol: '₨', name: 'Sri Lankan Rupee' },
    SYP: { symbol: '£', name: 'Syrian Pound' },
    TWD: { symbol: 'NT$', name: 'New Taiwan Dollar' },
    TJS: { symbol: 'SM', name: 'Tajikistani Somoni' },
    THB: { symbol: '฿', name: 'Thai Baht' },
    TRY: { symbol: '₺', name: 'Turkish Lira' },
    TMT: { symbol: 'T', name: 'Turkmenistani Manat' },
    AED: { symbol: 'د.إ', name: 'UAE Dirham' },
    UZS: { symbol: 'лв', name: 'Uzbekistani Som' },
    VND: { symbol: '₫', name: 'Vietnamese Dong' },
    YER: { symbol: '﷼', name: 'Yemeni Rial' },
    ALL: { symbol: 'L', name: 'Albanian Lek' },
    EUR: { symbol: '€', name: 'Euro' },
    BYN: { symbol: 'Br', name: 'Belarusian Ruble' },
    BAM: { symbol: 'KM', name: 'Bosnia-Herzegovina Mark' },
    BGN: { symbol: 'лв', name: 'Bulgarian Lev' },
    CZK: { symbol: 'Kč', name: 'Czech Koruna' },
    DKK: { symbol: 'kr', name: 'Danish Krone' },
    HUF: { symbol: 'Ft', name: 'Hungarian Forint' },
    ISK: { symbol: 'kr', name: 'Icelandic Króna' },
    MDL: { symbol: 'L', name: 'Moldovan Leu' },
    MKD: { symbol: 'ден', name: 'Macedonian Denar' },
    NOK: { symbol: 'kr', name: 'Norwegian Krone' },
    PLN: { symbol: 'zł', name: 'Polish Zloty' },
    RON: { symbol: 'lei', name: 'Romanian Leu' },
    RUB: { symbol: '₽', name: 'Russian Ruble' },
    RSD: { symbol: 'din', name: 'Serbian Dinar' },
    SEK: { symbol: 'kr', name: 'Swedish Krona' },
    CHF: { symbol: 'Fr', name: 'Swiss Franc' },
    UAH: { symbol: '₴', name: 'Ukrainian Hryvnia' },
    GBP: { symbol: '£', name: 'British Pound' },
    XCD: { symbol: '$', name: 'East Caribbean Dollar' },
    ARS: { symbol: '$', name: 'Argentine Peso' },
    BSD: { symbol: '$', name: 'Bahamian Dollar' },
    BBD: { symbol: '$', name: 'Barbadian Dollar' },
    BZD: { symbol: '$', name: 'Belize Dollar' },
    BOB: { symbol: 'Bs.', name: 'Bolivian Boliviano' },
    BRL: { symbol: 'R$', name: 'Brazilian Real' },
    CAD: { symbol: 'CA$', name: 'Canadian Dollar' },
    CLP: { symbol: '$', name: 'Chilean Peso' },
    COP: { symbol: '$', name: 'Colombian Peso' },
    CRC: { symbol: '₡', name: 'Costa Rican Colón' },
    CUP: { symbol: '$', name: 'Cuban Peso' },
    DOP: { symbol: '$', name: 'Dominican Peso' },
    USD: { symbol: '$', name: 'US Dollar' },
    GTQ: { symbol: 'Q', name: 'Guatemalan Quetzal' },
    GYD: { symbol: '$', name: 'Guyanese Dollar' },
    HTG: { symbol: 'G', name: 'Haitian Gourde' },
    HNL: { symbol: 'L', name: 'Honduran Lempira' },
    JMD: { symbol: '$', name: 'Jamaican Dollar' },
    MXN: { symbol: 'MX$', name: 'Mexican Peso' },
    NIO: { symbol: 'C$', name: 'Nicaraguan Córdoba' },
    PAB: { symbol: 'B/.', name: 'Panamanian Balboa' },
    PYG: { symbol: '₲', name: 'Paraguayan Guaraní' },
    PEN: { symbol: 'S/.', name: 'Peruvian Sol' },
    SRD: { symbol: '$', name: 'Surinamese Dollar' },
    TTD: { symbol: '$', name: 'Trinidad and Tobago Dollar' },
    UYU: { symbol: '$', name: 'Uruguayan Peso' },
    VES: { symbol: 'Bs.S', name: 'Venezuelan Bolívar' },
    AUD: { symbol: 'A$', name: 'Australian Dollar' },
    FJD: { symbol: '$', name: 'Fijian Dollar' },
    NZD: { symbol: 'NZ$', name: 'New Zealand Dollar' },
    PGK: { symbol: 'K', name: 'Papua New Guinean Kina' },
    WST: { symbol: 'T', name: 'Samoan Tālā' },
    SBD: { symbol: '$', name: 'Solomon Islands Dollar' },
    TOP: { symbol: 'T$', name: 'Tongan Paʻanga' },
    VUV: { symbol: 'Vt', name: 'Vanuatu Vatu' },
};

const DEFAULT_CURRENCY = 'USD';

/** Resolves an ISO-2 code (e.g. "UG", "SS") to a full country name.
 *  If already a full name, returns it unchanged. */
const resolveCountryName = (input) => {
  if (!input) return null;
  const trimmed = input.trim();
  // If it's a 2-letter code, map it; otherwise assume it's already a full name
  return (trimmed.length === 2 ? ISO2_TO_COUNTRY[trimmed.toUpperCase()] : trimmed) ?? trimmed;
};

/** Mirrors get_currency_for_country() in utils.py */
export const getCurrencyForCountry = (country) => {
  if (!country) return DEFAULT_CURRENCY;
  const name = resolveCountryName(country);
  return COUNTRY_CURRENCY_MAP[name] ?? DEFAULT_CURRENCY;
};

/** Mirrors get_currency_symbol() in utils.py
 *  Accepts ISO-2 country code ("UG"), full country name ("Uganda"),
 *  or currency code ("UGX") — all resolve correctly. */
export const getCurrencySymbol = (currencyCodeOrCountry) => {
  if (!currencyCodeOrCountry) return '$';
  // If it's a known currency code directly (e.g. "UGX"), use it straight away
  if (CURRENCY_META[currencyCodeOrCountry]) {
    return CURRENCY_META[currencyCodeOrCountry].symbol;
  }
  // Otherwise treat it as a country name or ISO-2 code
  const code = getCurrencyForCountry(currencyCodeOrCountry);
  return CURRENCY_META[code]?.symbol ?? code;
};

/** Mirrors get_currency_name() in utils.py */
export const getCurrencyName = (currencyCode) => {
  return CURRENCY_META[currencyCode]?.name ?? currencyCode;
};